### ISSUE TITLE
Doesn't work with Neon

### ISSUE THREAD

**Issue by mikejgray** [OpenVoiceOS/ovos-stt-plugin-fasterwhisper#1]
Running a Neon containerized dev setup, I get the following traceback:

```
neon-speech        | 2023-05-03 21:11:06.467 - voice - neon_speech.service:handle_internet_connected:395 - INFO - Internet Connected, Resetting STT Stream
neon-speech        | exception calling callback for <Future at 0x7f933b2d8820 state=finished raised AttributeError>
neon-speech        | Traceback (most recent call last):
neon-speech        |   File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 328, in _invoke_callbacks
neon-speech        |     callback(self)
neon-speech        |   File "/usr/local/lib/python3.8/site-packages/pyee/_executor.py", line 56, in _callback
neon-speech        |     self.emit('error', exc)
neon-speech        |   File "/usr/local/lib/python3.8/site-packages/pyee/_base.py", line 116, in emit
neon-speech        |     self._emit_handle_potential_error(event, args[0] if args else None)
neon-speech        |   File "/usr/local/lib/python3.8/site-packages/pyee/_base.py", line 86, in _emit_handle_potential_error
neon-speech        |     raise error
neon-speech        |   File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
neon-speech        |     result = self.fn(*self.args, **self.kwargs)
neon-speech        |   File "/usr/local/lib/python3.8/site-packages/neon_speech/service.py", line 396, in handle_internet_connected
neon-speech        |     self.loop.stt.results_event.set()
neon-speech        | AttributeError: 'OVOSHTTPServerSTT' object has no attribute 'results_event'
```

**Comment by JarbasAl** [comment]
this is a Neon bug, Neon patches plugins to add that results_event (don't remember why)

since that is breaking the actual internals of OPM the bug should be raised in neon_speech repo instead

@NeonDaniel
